travis:
  secure:
    BINSTAR_TOKEN: NTqwQxPogPuRTANnX0sMGng1+iW2PdLW6ajSgW0hb+N1pUL7cWs2iwGI4NT1V5H5BRcdwN3SXGgfymVVfu2sSEWLJgEEFasqi87bz/epRuXrvznRJSJ4NUiAiUxfx8Og4bK6Jhue8pbOZkf6+8uUXv9Qtv0svoqq3pZzzPwHBJVVeyqmGBnle8gXhkhZjtaKUCIFY/LTW5vYmL/tCEPa7EDYg+dyPb8LX0CTcpKiutW5if8G22FBuCQPWzzBgjNiCCfZ+T/6daZiEEIgLEq2CkPyOy7PLK8NFmB3SjFGU/uWx6lsazSsOQ41Uk20fPqLcDlQLrcBIst87JZNz1+33mdm+dVsdgBNSIKSNCUA41rgVAa6Sb/zXel7Wb5+m82j3E8z9MgA0EeyVSYNOzqrFYuIp3irbflePt8WJ4a4Ds+/bMS623oFtnH2SKxGWoADmVScXs/FXjzBM1rpNJ5nncGkFoohaNMy1sSkOqCkjXkcroh+towNxloJ71DShSvEnqLOuP90iDKzA9/jqD8shlvZmfCATXVbHKl5IvLVYSDkjiaNJzEEE5G3i2+/opESdFvHksEdsF7ZslMAgbB4Z4YKn3KReatNfaJI8rhpwFfs5CZZBT9dKCSXccHW/CFx0esZEGwefCBqDZ8DnGaTQJ0IkTqdm401Uds2adLvkS4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
