travis:
  secure:
    BINSTAR_TOKEN: KnhcTfuuQexEAV4SgtrjJOGjl09cOSPPTYVOcsm8mRUGXrGrylT2N4SHgrk1UnBt2v59GvqzQU7MsTvcb8P8uodNW02wV36elH5TbeY045IpZLlHLo8qLHCJCH7PMEw1nA83roMcS2W61dgV/lo+43m18UCC2p46PF05k3JAm/kBh1TLpQxT3NICHlr6PddzjHHo0ET7g2Huyuz9HHmkRKWqj4it9L6CqOKu5Sd7o4D9D4sGWqugAzsQ0SAL4sMj79DzPnhgDf4yIKFbfnM7oUudavGp3/JfwRhqF4yqP/vwFirimZVHyenvHJRuB+Zz8zLv92hEMrVkRiF3X0nXj+qTV4ZDGx9/HZmkP3IEzeUIB+CCYKVGXTc7YDZ/qSDwnfTNliJExXQs8AojP6CzUftWzOEA2HN4sN+II+5CJ06P+2e088TT/fFKnA0awtU9yCNtD/oCrjMN+L76iCdhNVNlDnH4jHNZnXKOETXDfn3+mH+TeFZhRoOilY5YPYwgyM9vld+vHoRQWrUzEgTc0A2HwIbCcq5RbJQRH/0lsoGmhJe/foJew/YsllhXhZlYe/LR/SEt3Hvvc7LSaPGjkS25L5mSgMT+3V7e77CZsrlizXWSyqZ510iCPxsqU8/8ggJ7YPUSKVu7GBreKqUO+uiopsqYs9eYFWNMv78bS3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
