travis:
  secure:
    BINSTAR_TOKEN: aDR4oSCyCHVf10Flgiu6LdbVTsrSG6PjxmtvwYX7EXnrPX2Sx6xzhqH9Hq+sugo9QcH00o49CQhA09anS7vv4yj+xEE2eTmkB/Dm1PnjmiaKGk8KiAM/bBn60huUTx0KdmmMJ9sWUokaL7qQh8ZxMw5MVahn3U3JcSXtiC2PFAw5zUPR7LNKcFrqdJPKTnIrdPWaqklfrxgOmQnjporw1AvFSkw6WF8gv6yLekFZAat9THtvu+lJFFTrJQ7uGbAQaoQRnuQwf/c6S2EZ8UrqHOOKpE47szNS8TPXt07pXAwYmfLGN4SIPjCH3SGWCCBmHAyJppKiVmGRL026PUSCJ0shiwQyDI+sVZjTDPwGxT6W6GnIk8N1syxKE8yGad2LbWivOeWEXst715JXAgmzqitrtcVmnuMEAsDXo3jlVOUJUwv+Z77rthw/qVXw0MNfKM5HoAdMaGEfdpsMfyJPMi9pxtWOUdF4w8V3OPFm6tJdrKXbP1dJcrWX1/VN1ZYdYP+vLZ/TrquCR+UMZKMLt79PSqvfLHMG/T6oyY1BcUOUaUrYssLSgMTs/8miDC3rF4UulepNt1zfck57jGLKldZkvPfadtJSYTL9OKFfJKPATfyXypHBoMOipG8xYUuQe2D2eyQtT1q7o4eXN+IcLHknE0PPk7QrTQkPaD9ehco=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
